case "GOOGL": return "Mountain View, CA"
case "MSFT": return "Redmond, WA"
case "FB": return "Menlo Park, CA"
case "AABA": return "New York, NY"
case "SNAP": return "Venice, CA"
case "TWTR": return "San Francisco, CA"
case "IAC": return "New York City, NY"
case "TRIP": return "Needham, MA"
case "TTD": return "Ventura, CA"
case "ROKU": return "Los Gatos, CA"
case "P": return "Oakland, CA"
case "QUOT": return "Mountain View, CA"
case "BCOR": return "Bellevue, WA"
case "RATE": return "New York, NY"
case "XOXO": return "New York, NY"
case "TTGT": return "Newton, MA"
case "RUBI": return "Los Angeles, CA"


case "AMZN": return "Seattle, WA"
case "PCLN": return "Norwalk, CT"
case "NFLX": return "Los Gatos, CA"
case "PYPL": return "San Jose, CA"
case "EBAY": return "San Jose, CA"
case "EXPE": return "Bellevue, WA"
case "SQ": return "San Francisco, CA"
case "GDDY": return "Scottsdale, AZ"
case "MTCH": return "Dallas, TX"
case "ZG": return "Seattle, WA"
case "W": return "Boston, MA"
case "TRIP": return "Needham, MA"
case "GRUB": return "Chicago, IL"
case "STMP": return "El Segundo, CA"
case "YELP": return "San Francisco, CA"
case "EIGI": return "Burlington, MA"
case "RDFN": return "Seattle, WA"
case "ZNGA": return "San Francisco, CA"
case "GRPN": return "Chicago, IL"
case "LC": return "San Francisco, CA"
case "SFLY": return "Redwood City, CA"
case "WEB": return "Jacksonville, FL"
case "ETSY": return "Brooklyn, NY"
case "CHGG": return "Santa Clara, CA"
case "APRN": return "New York, NY"
case "SSTK": return "New York, NY"
case "OSTK": return "Midvale, UT"
case "PETS": return "Delray Beach, FL"
case "FLWS": return "Carle Place, NY"
case "CRCM": return "Waltham, MA"
case "TZOO": return "New York, NY"


case "NKE": return "Beaverton, OR"
case "SBUX": return "Seattle, WA"
case "UA": return "Baltimore, MD"
case "GPRO": return "San Mateo, CA"
case "FIT": return "San Francisco, CA"


case "AAPL": return "Cupertino, CA"
case "T": return "Dallas, TX"
case "VZ": return "New York, NY"
case "CMCS.A": return "Philadelphia, PA"
case "DIS": return "Burbank, CA"
case "TWX": return "New York, NY"
case "S": return "Overland Park, KS"
case "DISH": return "Englewood, CO"
case "SIRI": return "New York, NY"
case "CBS": return "New York, NY"
case "VIAB": return "New York, NY"
case "NWSA": return "New York, NY"


case "AKAM": return "Cambridge, MA"
case "TTD": return "Ventura, CA"
case "NEWR": return "San Francisco, CA"
case "LLNW": return "Tempe, AZ"
case "BV": return "Austin, TX"
case "ECOM": return "Morrisville, NC"
case "BCOV": return "Boston, MA"
case "PFSW": return "Allen, TX"
case "RNWK": return "Seattle, WA"
