case "AAPL": return "Cupertino, CA"
case "GOOGL": return "Mountain View, CA"
case "MSFT": return "Redmond, WA"
case "ORCL": return "Redwood City, CA"
case "IBM": return "Armonk, NY"
case "CSCO": return "San Jose, CA"
case "HPQ": return "Palo Alto, CA"


case "ADBE": return "San Jose, CA"
case "INTU": return "Mountain View, CA"
case "ADSK": return "San Rafael, CA"
case "NUAN": return "Burlington, MA"
case "FICO": return "San Jose, CA"
case "PEGA": return "Cambridge, MA"
case "MANH": return "Atlanta, GA"
case "CALD": return "Dublin, CA"
case "TYPE": return "Woburn, MA"
case "PRO": return "Houston, TX"
case "MODN": return "Redwood City, CA"
case "EGAN": return "Sunnyvale, CA"


case "ADSK": return "San Rafael, CA"
case "SNPS": return "Mountain View, CA"
case "CDNS": return "San Jose, CA"
case "ANSS": return "Canonsburg, PA"
case "PTC": return "Needham, MA"
case "AZPN": return "Bedford, MA"
case "EXA": return "Burlington, MA"


case "SSNC": return "Windsor, CT"
case "BR": return "Lake Success, NY"
case "FDS": return "Norwalk, CT"
case "FICO": return "San Jose, CA"
case "ACIW": return "Naples, FL"
case "QTWO": return "Austin, TX"
case "EPAY": return "Portsmouth, NH"


case "ATVI": return "Santa Monica, CA"
case "EA": return "Redwood City, CA"
case "TTWO": return "New York, NY"
case "ZNGA": return "San Francisco, CA"


case "VMW": return "Palo Alto, CA"
case "RHT": return "Raleigh, NC"
case "CTXS": return "Fort Lauderdale, FL"
case "OTEX": return "Waterloo, ON"
case "NTNX": return "San Jose, CA"
case "PRGS": return "Bedford, MA"
case "ATEN": return "San Jose, CA"
case "AVID": return "Burlington, MA"


case "SPLK": return "San Francisco, CA"
case "DATA": return "Seattle, WA"
case "NEWR": return "San Francisco, CA"
case "VRNS": return "New York, NY"
case "HDP": return "Santa Clara, CA"
case "MSTR": return "Tysons Corner, VA"


case "SYMC": return "Mountain View, CA"
case "NOW": return "Santa Clara, CA"
case "CA": return "New York, NY"
case "NTCT": return "Westford, MA"
case "CVLT": return "Tinton Falls, NJ"


case "AKAM": return "Cambridge, MA"
case "GDDY": return "Scottsdale, AZ"
case "EIGI": return "Burlington, MA"
case "BSFT": return "Gaithersburg, MD"
case "LLNW": return "Tempe, AZ"
case "PFSW": return "Allen, TX"
case "RNWK": return "Seattle, WA"


case "ADBE": return "San Jose, CA"
case "CRM": return "San Francisco, CA"
case "INTU": return "Mountain View, CA"
case "ADSK": return "San Rafael, CA"
case "WDAY": return "Pleasanton, CA"
case "NOW": return "Santa Clara, CA"
case "SQ": return "San Francisco, CA"
case "LOGM": return "Boston, MA"
case "ULTI": return "Weston, FL"
case "PAYC": return "Oklahoma City, OK"
case "PFPT": return "Sunnyvale, CA"
case "RNG": return "Belmont, CA"
case "HUBS": return "Cambridge, MA"
case "ZEN": return "San Francisco, CA"
case "TWLO": return "San Francisco, CA"
case "TTD": return "Ventura, CA"
case "BOX": return "Redwood City, CA"
case "PCTY": return "Arlington Heights, IL"
case "CSOD": return "Santa Monica, CA"
case "BL": return "Los Angeles, CA"
case "QLYS": return "Redwood City, CA"
case "CALD": return "Dublin, CA"
case "FIVN": return "San Ramon, CA"
case "EGHT": return "San Jose, CA"
case "WK": return "Ames, IA"
case "LPSN": return "New York, NY"
case "APTI": return "Bellevue, WA"
case "BV": return "Austin, TX"
case "SREV": return "Denver, CO"
case "BCOV": return "Boston, MA"
case "SYNC": return "Buffalo, NY"
case "MRIN": return "San Francisco, CA"


case "SYMC": return "Mountain View, CA"
case "PANW": return "Santa Clara, CA"
case "FTNT": return "Sunnyvale, CA"
case "PFPT": return "Sunnyvale, CA"
case "FEYE": return "Milpitas, CA"
case "QLYS": return "Redwood City, CA"
case "IMPV": return "Redwood Shores, CA"
case "CUDA": return "Campbell, CA"
case "SCWX": return "Atlanta, GA"
case "RPD": return "Boston, MA"
case "VDSI": return "Oakbrook Terrace, IL"
case "MOBL": return "Mountain View, CA"
case "ZIXI": return "Dallas, TX"


case "VRSN": return "Reston, VA"
case "DOX": return "Chesterfield, MO"
case "RNG": return "Belmont, CA"
case "BSFT": return "Gaithersburg, MD"
case "SNCR": return "Bridgewater, NJ"
case "SONS": return "Westford, MA"
case "IPAS": return "Redwood Shores, CA"


case "ADSK": return "San Rafael, CA"
case "TRMB": return "Sunnyvale, CA"
case "VEEV": return "Pleasanton, CA"
case "GWRE": return "Foster City, CA"
case "AZPN": return "Bedford, MA"
case "ATHN": return "Watertown, MA"
case "BLKB": return "Charleston, SC"
case "MDSO": return "New York, NY"
case "RP": return "Richardson, TX"
case "TWOU": return "Lanham, MD"
case "ELLI": return "Pleasanton, CA"
case "INOV": return "Bowie, MD"
case "ALRM": return "Tysons, VA"
case "QTWO": return "Austin, TX"
case "TDOC": return "Purchase, NY"
case "MB": return "San Luis Obispo, CA"
case "INST": return "Salt Lake City, UT"
case "CSLT": return "San Francisco, CA"
case "UPLD": return "Austin, TX"


case "TYL": return "Plano, TX"
case "NATI": return "Austin, TX"
case "EBIX": return "Johns Creek, GA"


case "MCK": return "San Francisco, CA"
case "CERN": return "North Kansas City, MO"
case "ATHN": return "Watertown, MA"
case "MDRX": return "Chicago, IL"
case "INOV": return "Bowie, MD"
case "QSII": return "Irvine, CA"
case "CSLT": return "San Francisco, CA"


case "LOPE": return "Phoenix, AZ"
case "TWOU": return "Lanham, MD"
case "CHGG": return "Santa Clara, CA"
case "INST": return "Salt Lake City, UT"
case "STRA": return "Herndon, VA"
case "CPLA": return "Minneapolis, MN"
case "LRN": return "Herndon, VA"
case "RST": return "Arlington, VA"
case "APEI": return "Charles Town, WV"
