case "GOOGL": return "Alphabet Inc., through its subsidiaries, provides online advertising services in the United States, the United Kingdom, and rest of the world."
case "MSFT": return "Microsoft Corporation develops, licenses, and supports software products, services, and devices worldwide."
case "FB": return "Facebook, Inc. provides various products to connect and share through mobile devices, personal computers, and other surfaces worldwide."
case "AABA": return "Altaba Inc. operates as a non-diversified, closed-end management investment company in the United States."
case "SNAP": return "Snap Inc. operates as a camera company."
case "TWTR": return "Twitter, Inc. operates as a global platform for public self-expression and conversation in real time."
case "IAC": return "IAC/InterActiveCorp, together with its subsidiaries, operates as a media and Internet company in the United States and internationally."
case "TRIP": return "TripAdvisor, Inc. operates as an online travel company."
case "TTD": return "The Trade Desk, Inc., a technology company, operates a self-service cloud-based platform that enables advertising buyers to create, manage, and optimize data-driven digital advertising campaigns using their own teams in the United States and internationally."
case "ROKU": return "Roku, Inc. primarily operates a TV streaming platform."
case "P": return "Pandora Media, Inc. provides Internet music platform services in North America."
case "QUOT": return "Quotient Technology Inc. provides digital platform that enables consumer packaged goods (CPGs) brands and retailers in the United States."
case "BCOR": return "Blucora, Inc. provides technology-enabled financial solutions to consumers, small business owners, and tax professionals in the United States."
case "RATE": return "Bankrate, Inc. operates as a publisher, aggregator, and distributor of personal finance content on the Internet."
case "XOXO": return "XO Group Inc. provides multiplatform media and marketplace services to the wedding, pregnancy and parenting, nesting, and local entertainment markets."
case "TTGT": return "TechTarget, Inc. provides specialized online content for buyers of corporate information technology (IT) products and services; and purchase-intent marketing and sales services for enterprise technology vendors in the United States and internationally."
case "RUBI": return "The Rubicon Project, Inc., a technology company, engages in automating the purchasing and selling of advertising."


case "AMZN": return "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally."
case "PCLN": return "The Priceline Group Inc. provides online travel and restaurant reservation, and related services."
case "NFLX": return "Netflix, Inc., an Internet television network, engages in the Internet delivery of television (TV) shows and movies on various Internet-connected screens."
case "PYPL": return "PayPal Holdings, Inc. operates as a technology platform company that enables digital and mobile payments on behalf of consumers and merchants worldwide."
case "EBAY": return "eBay Inc. operates commerce platforms that connect various buyers and sellers worldwide."
case "EXPE": return "Expedia, Inc., together with its subsidiaries, operates as an online travel company in the United States and internationally."
case "SQ": return "Square, Inc. develops and provides payment processing, point-of-sale (POS), financial, and marketing services worldwide."
case "GDDY": return "GoDaddy Inc. designs and develops cloud-based technology products for small businesses, Web design professionals, and individuals in the United States and internationally."
case "MTCH": return "Match Group, Inc. provides dating products."
case "ZG": return "Zillow Group, Inc. operates real estate and home-related information marketplaces on mobile and the Web in the United States."
case "W": return "Wayfair Inc. engages in the e-commerce business in the United States and Europe."
case "TRIP": return "TripAdvisor, Inc. operates as an online travel company."
case "GRUB": return "GrubHub Inc., together with its subsidiaries, provides an online and mobile platform for restaurant pick-up and delivery orders in the United States."
case "STMP": return "Stamps.com Inc. provides Internet-based mailing and shipping solutions in the United States."
case "YELP": return "Yelp Inc. operates a platform that connects people with local businesses in the United States, Canada, and internationally."
case "EIGI": return "Endurance International Group Holdings, Inc., together with its subsidiaries, provides cloud-based platform solutions for small-and medium-sized businesses worldwide."
case "RDFN": return "Redfin Corporation operates as a real estate brokerage company in the United States."
case "ZNGA": return "Zynga Inc. develops, markets, and operates social games as live services played on the Internet, social networking sites, and mobile platforms in the United States and internationally."
case "GRPN": return "Groupon, Inc. operates online local commerce marketplaces that connect merchants to consumers by offering goods and services at a discount in North America, Europe, the Middle East, Africa, and internationally."
case "LC": return "LendingClub Corporation, together with its subsidiaries, operates as an online marketplace that connects borrowers and investors in the United States."
case "SFLY": return "Shutterfly, Inc. manufactures and retails personalized products and services primarily in the United States and Canada, as well as in the European Community."
case "WEB": return "Web.com Group, Inc. provides a range of Internet services to small businesses in North America, South America, and the United Kingdom."
case "ETSY": return "Etsy, Inc. operates as a commerce platform to make, sell, and buy goods online and offline worldwide."
case "CHGG": return "Chegg, Inc. operates student-first connected learning platform that help students transition from high school to college to career."
case "APRN": return "Blue Apron Holdings, Inc. operates an e-commerce marketplace that delivers original recipes and fresh ingredients for making home cooking accessible."
case "SSTK": return "Shutterstock, Inc. provides content products and services in North America, Europe, and internationally."
case "OSTK": return "Overstock.com, Inc. operates as an online retailer in the United States."
case "PETS": return "PetMed Express, Inc. and its subsidiaries, doing business as 1-800-PetMeds, operates as a pet pharmacy in the United States."
case "FLWS": return "1-800-Flowers.com, Inc., together with its subsidiaries, provides gourmet food and floral gifts for various occasions in the United States."
case "CRCM": return "Care.com, Inc. operates an online marketplace for finding and managing family care in the United States and internationally."
case "TZOO": return "Travelzoo Inc., together with its subsidiaries, provides travel, entertainment, and local deals from travel and entertainment companies, and local businesses in the Asia Pacific, Europe, and North America."


case "NKE": return "NIKE, Inc., together with its subsidiaries, designs, develops, markets, and sells athletic footwear, apparel, equipment, and accessories worldwide."
case "SBUX": return "Starbucks Corporation, together with its subsidiaries, operates as a roaster, marketer, and retailer of specialty coffee worldwide."
case "UA": return "Under Armour, Inc., together with its subsidiaries, develops, markets, and distributes branded performance apparel, footwear, and accessories for men, women, and youth primarily in North America, Europe, the Middle East, Africa, the Asia-Pacific, and Latin America."
case "GPRO": return "GoPro, Inc. develops and sells mountable and wearable cameras, and accessories in the United States and internationally."
case "FIT": return "Fitbit, Inc. designs and sells connected health and fitness tracking devices."


case "AAPL": return "Apple Inc. designs, manufactures, and markets mobile communication and media devices, personal computers, and portable digital music players to consumers, small and mid-sized businesses, and education, enterprise, and government customers worldwide."
case "T": return "AT&T Inc. provides telecommunications and digital entertainment services."
case "VZ": return "Verizon Communications Inc., through its subsidiaries, provides communications, information, and entertainment products and services to consumers, businesses, and governmental agencies worldwide."
case "CMCS.A": return "Comcast Corporation operates as a media and technology company worldwide."
case "DIS": return "The Walt Disney Company, together with its subsidiaries, operates as an entertainment company worldwide."
case "TWX": return "Time Warner Inc. operates as a media and entertainment company in the United States and internationally."
case "S": return "Sprint Corporation, through its subsidiaries, provides various wireless and wireline communications products and services to consumers, businesses, government subscribers, and resellers in the United States, Puerto Rico, and the U.S. Virgin Islands."
case "DISH": return "DISH Network Corporation, together with its subsidiaries, provides pay-TV services in the United States."
case "SIRI": return "Sirius XM Holdings Inc. provides satellite radio services in the United States."
case "CBS": return "CBS Corporation operates as a mass media company worldwide."
case "VIAB": return "Viacom, Inc. operates as media brand worldwide."
case "NWSA": return "News Corporation, a media and information services company, creates and distributes content for consumers and businesses worldwide."


case "AKAM": return "Akamai Technologies, Inc. provides cloud services for delivering, optimizing, and securing content and business applications over the Internet in the United States and internationally."
case "TTD": return "The Trade Desk, Inc., a technology company, operates a self-service cloud-based platform that enables advertising buyers to create, manage, and optimize data-driven digital advertising campaigns using their own teams in the United States and internationally."
case "NEWR": return "New Relic, Inc., a software-as-a-service company, provides digital intelligence products worldwide."
case "LLNW": return "Limelight Networks, Inc. provides content delivery network services to deliver digital content over the Internet in the Americas, Europe, the Middle East, Africa, and the Asia Pacific."
case "BV": return "Bazaarvoice, Inc. provides marketing tools to retailer and brand clients for understanding consumer voice."
case "ECOM": return "ChannelAdvisor Corporation provides software-as-a-service solutions worldwide."
case "BCOV": return "Brightcove Inc. provides cloud-based services for video."
case "PFSW": return "PFSweb, Inc. provides omni-channel commerce solutions in the United States, Europe, Canada, and India."
case "RNWK": return "RealNetworks, Inc. provides network-delivered digital media applications and services to manage, play, and share digital media."
