case "GOOGL": return "Alphabet"
case "MSFT": return "Microsoft "
case "FB": return "Facebook"
case "AABA": return "Altaba"
case "SNAP": return "Snap"
case "TWTR": return "Twitter"
case "IAC": return "Iac/Interactive"
case "TRIP": return "Tripadvisor "
case "TTD": return "The Trade Desk"
case "ROKU": return "Roku"
case "P": return "Pandora Media"
case "QUOT": return "Quotient (Fka Coupons.Com)"
case "BCOR": return "Blucora"
case "RATE": return "Bankrate"
case "XOXO": return "Xo Group"
case "TTGT": return "Techtarget"
case "RUBI": return "Rubicon Project"


case "AMZN": return "Amazon.Com "
case "PCLN": return "Priceline.Com "
case "NFLX": return "Netflix  "
case "PYPL": return "Paypal"
case "EBAY": return "Ebay "
case "EXPE": return "Expedia "
case "SQ": return "Square"
case "GDDY": return "Godaddy"
case "MTCH": return "Match"
case "ZG": return "Zillow  "
case "W": return "Wayfair"
case "TRIP": return "Tripadvisor "
case "GRUB": return "Grubhub"
case "STMP": return "Stamps.Com "
case "YELP": return "Yelp  "
case "EIGI": return "Endurance International Group"
case "RDFN": return "Redfin"
case "ZNGA": return "Zynga  "
case "GRPN": return "Groupon  "
case "LC": return "Lending Club"
case "SFLY": return "Shutterfly  "
case "WEB": return "Web.Com "
case "ETSY": return "Etsy"
case "CHGG": return "Chegg  "
case "APRN": return "Blue Apron"
case "SSTK": return "Shutterstock  "
case "OSTK": return "Overstock.Com "
case "PETS": return "Petmed Express"
case "FLWS": return "1-800-Flowers.Com "
case "CRCM": return "Care.Com  "
case "TZOO": return "Travelzoo "


case "NKE": return "Nike"
case "SBUX": return "Starbucks"
case "UA": return "Under Armour"
case "GPRO": return "Gopro"
case "FIT": return "Fitbit"


case "AAPL": return "Apple"
case "T": return "At&T  "
case "VZ": return "Verizon Communications"
case "CMCS.A": return "Comcast "
case "DIS": return "The Walt Disney Company"
case "TWX": return "Time Warner"
case "S": return "Sprint "
case "DISH": return "Dish Network"
case "SIRI": return "Sirius Xm"
case "CBS": return "Cbs "
case "VIAB": return "Viacom  "
case "NWSA": return "News Corp"


case "AKAM": return "Akamai Technologies"
case "TTD": return "The Trade Desk"
case "NEWR": return "New Relic"
case "LLNW": return "Limelight Networks"
case "BV": return "Bazaarvoice  "
case "ECOM": return "Channeladvisor "
case "BCOV": return "Brightcove"
case "PFSW": return "Pfsweb "
case "RNWK": return "Realnetworks "
